name: cmdhelp
version: '1.0.3'
summary: Command finder tool with Tkinter GUI
description: |
  A utility that finds terminal commands built with Python and Tkinter.

grade: stable
confinement: strict
base: core24

apps:
  cmdhelp:
    command: bin/python3 $SNAP/lib/python3.12/site-packages/cmdhelp.py
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland

parts:
  cmdhelp-code:
    plugin: dump
    source: .
    stage-packages:
      - python3-tk
